del thesis_report.aux
del thesis_report.pdf
del thesis_report.synctex.gz
del thesis_report.log
del thesis_report.blg
del thesis_report.bbl
del thesis_report.toc
del thesis_report.loa
del thesis_report.lof
del thesis_report.lot