/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sdeckers' at '19.01.17 15:14' with Gradle 2.14.1
 *
 * @author sdeckers, @date 19.01.17 15:14
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
